// interfaces/payment.interface.ts

import { ObjectId } from "mongoose";

export interface IPayment {
  _id?: string; // Optional, as it will be generated by MongoDB
  user_id: ObjectId;
  guide_id: ObjectId;
  amount: number;
  commission: number; // Admin's commission
  netAmount: number; // Amount transferred to the Guide
  paymentStatus: 'pending' | 'completed' | 'refunded'; // Current payment status
  transactionId: string; // PayPal Transaction ID
  paymentMethod: 'paypal'; // Payment method used
  createdAt: Date; // Date of payment creation
  updatedAt?: Date; // Optional field, for when status changes
}
