import { ObjectId } from "mongoose";

export interface IReport {
    _id?: string; // Optional, as it will be generated by MongoDB
    userId?: ObjectId; // Reference to the user's ID
    reportId?: ObjectId; // Reference to the report user's ID (optional for Seeker's first payment)
    comment? : string;
  }